#!/usr/bin/env python3
"""Extract short-code (1~2 key) entries from the bundled flypy dict files
and emit data/xhup_shortcodes.js.

A "short code" here means an input sequence of length 1 or 2 that lets the
user pick a character/word as the first candidate without typing the full
4-letter code. We use the bundled Rime dict files as the source of truth:

- xhup.primary.dict.yaml  -> sort: original, every short code has a unique
  entry which is by definition the first candidate at that input. Tagged
  as `primary` (一简/二简首选).
- xhup.single.code.dict.yaml -> 26 一简词 (a..z) candidates. Tagged as
  `single` (一简词).
- xhup.secondary.dict.yaml -> 次选 short codes, tagged `secondary`.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DICT_DIR = os.path.join(ROOT, 'third_party', 'rime-crane-xhup')
OUT_PATH = os.path.join(ROOT, 'data', 'xhup_shortcodes.js')

FILES = [
    ('primary', 'xhup.primary.dict.yaml'),
    ('single', 'xhup.single.code.dict.yaml'),
    ('secondary', 'xhup.secondary.dict.yaml'),
]

MAX_CODE_LEN = 2  # only 1- or 2-key shortcuts


def parse(path):
    rows = []
    in_data = False
    with open(path, encoding='utf8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not in_data:
                if line.strip() == '...':
                    in_data = True
                continue
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) < 2:
                continue
            word, code = parts[0].strip(), parts[1].strip()
            if not word or not code:
                continue
            rows.append((word, code))
    return rows


def is_single_char(s):
    # Treat any single user-perceived character (one codepoint here is fine
    # because the source dict uses BMP chars almost exclusively).
    return len(s) == 1


def main():
    chars = {}
    words = {}
    for tag, fname in FILES:
        path = os.path.join(DICT_DIR, fname)
        for word, code in parse(path):
            if len(code) > MAX_CODE_LEN:
                continue
            if not code.isascii() or not code.isalpha():
                continue
            entry = {'c': code, 't': tag}
            bucket = chars if is_single_char(word) else words
            existing = bucket.setdefault(word, [])
            # Dedup: skip if any entry with the same code already exists
            # (earlier tags in FILES win, per FILES iteration order).
            if not any(e['c'] == code for e in existing):
                existing.append(entry)

    # Sort each entry list: shorter code first, then tag priority
    tag_order = {'primary': 0, 'single': 1, 'secondary': 2}
    for bucket in (chars, words):
        for k, v in bucket.items():
            v.sort(key=lambda e: (len(e['c']), tag_order.get(e['t'], 9), e['c']))

    payload = {
        'meta': {
            'name': '小鹤音形 v10.9s 一/二简短码索引',
            'maxCodeLen': MAX_CODE_LEN,
            'sourceFiles': [f for _, f in FILES],
            'charCount': len(chars),
            'wordCount': len(words),
        },
        'chars': chars,
        'words': words,
    }
    out = '/* Auto-generated by tools/build_shortcodes.py. Do not edit by hand. */\n'
    out += 'window.XHUP_SHORTCUTS = ' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n'
    with open(OUT_PATH, 'w', encoding='utf8') as f:
        f.write(out)
    print('wrote', OUT_PATH, 'chars=', len(chars), 'words=', len(words))


if __name__ == '__main__':
    main()
